# Generated by Django 5.2.12 on 2026-03-13 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mmr_version_id", models.PositiveIntegerField(blank=True, null=True)),
                ("batch_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("awaiting_pre_qa", "Awaiting Pre-QA"),
                            ("in_pre_qa_review", "In Pre-QA Review"),
                            ("awaiting_quality_review", "Awaiting Quality Review"),
                            ("in_quality_review", "In Quality Review"),
                            ("returned_for_correction", "Returned for Correction"),
                            ("released", "Released"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("snapshot_json", models.JSONField()),
                (
                    "lot_size_target",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "lot_size_actual",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                ("batch_context_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "batches",
            },
        ),
        migrations.CreateModel(
            name="BatchStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("step_key", models.CharField(max_length=100)),
                ("occurrence_key", models.CharField(default="default", max_length=100)),
                ("occurrence_index", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                ("sequence_order", models.PositiveIntegerField()),
                ("is_applicable", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("signed", "Signed"),
                        ],
                        default="not_started",
                        max_length=32,
                    ),
                ),
                (
                    "signature_state",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("required", "Required"),
                            ("signed", "Signed"),
                        ],
                        default="not_required",
                        max_length=32,
                    ),
                ),
                ("blocks_execution_progress", models.BooleanField(default=False)),
                ("blocks_step_completion", models.BooleanField(default=True)),
                ("blocks_signature", models.BooleanField(default=False)),
                ("blocks_pre_qa_handoff", models.BooleanField(default=True)),
                ("required_data_complete", models.BooleanField(default=True)),
                ("changed_since_review", models.BooleanField(default=False)),
                ("changed_since_signature", models.BooleanField(default=False)),
                ("review_required", models.BooleanField(default=False)),
                ("has_open_exception", models.BooleanField(default=False)),
                ("open_exception_is_blocking", models.BooleanField(default=False)),
                ("data_json", models.JSONField(default=dict)),
                ("meta_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="batches.batch",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edited_batch_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="DossierChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("document_name", models.CharField(max_length=200)),
                ("is_present", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="batches.batch",
                    ),
                ),
            ],
            options={
                "ordering": ("document_name",),
            },
        ),
        migrations.CreateModel(
            name="StepSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meaning", models.CharField(max_length=50)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="step_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to="batches.batchstep",
                    ),
                ),
            ],
            options={
                "ordering": ("-signed_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="batchstep",
            constraint=models.UniqueConstraint(
                fields=("batch", "step_key", "occurrence_key"), name="uniq_batch_step_occurrence"
            ),
        ),
        migrations.AddConstraint(
            model_name="dossierchecklistitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "document_name"), name="batches_unique_checklist_document"
            ),
        ),
    ]
