# Generated by Django 5.2.12 on 2026-03-13 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mmr", "0001_initial_mmr_models"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("batch_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("in_execution", "In execution"),
                            ("in_progress", "In Progress"),
                            ("awaiting_pre_qa", "Awaiting Pre-QA"),
                            ("in_pre_qa_review", "In Pre-QA Review"),
                            ("awaiting_quality_review", "Awaiting Quality Review"),
                            ("in_quality_review", "In Quality Review"),
                            ("returned_for_correction", "Returned for Correction"),
                            ("review_required", "Review required"),
                            ("under_review", "Under review"),
                            ("released", "Released"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("batch_context_json", models.JSONField(blank=True, default=dict)),
                ("snapshot_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mmr_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="mmr.mmrversion",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "batches",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BatchStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("reference", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("signed", "Signed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("requires_signature", models.BooleanField(default=False)),
                ("required_data_complete", models.BooleanField(default=True)),
                ("changed_since_review", models.BooleanField(default=False)),
                ("changed_since_signature", models.BooleanField(default=False)),
                ("review_required", models.BooleanField(default=False)),
                ("has_open_exception", models.BooleanField(default=False)),
                ("open_exception_is_blocking", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="batches.batch",
                    ),
                ),
            ],
            options={
                "ordering": ("batch", "order"),
            },
        ),
        migrations.CreateModel(
            name="DossierChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("document_name", models.CharField(max_length=200)),
                ("is_present", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="batches.batch",
                    ),
                ),
            ],
            options={
                "ordering": ("document_name",),
            },
        ),
        migrations.CreateModel(
            name="StepSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meaning", models.CharField(max_length=50)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="step_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to="batches.batchstep",
                    ),
                ),
            ],
            options={
                "ordering": ("-signed_at",),
            },
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["site", "status"], name="batch_site_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="batchstep",
            constraint=models.UniqueConstraint(
                fields=("batch", "order"), name="batches_unique_step_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="dossierchecklistitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "document_name"), name="batches_unique_checklist_document"
            ),
        ),
    ]
