# Generated by Django 5.2.12 on 2026-03-13 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("batch_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("in_execution", "In execution"),
                            ("review_required", "Review required"),
                            ("under_review", "Under review"),
                            ("released", "Released"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("required", "Required"),
                            ("in_review", "In review"),
                            ("reviewed", "Reviewed"),
                            ("changed_since_review", "Changed since review"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "signature_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("required", "Required"),
                            ("partially_signed", "Partially signed"),
                            ("signed", "Signed"),
                            ("changed_since_signature", "Changed since signature"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "lot_size_target",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "lot_size_actual",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                ("snapshot_json", models.JSONField()),
                ("batch_context_json", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("review_started_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "batches",
            },
        ),
        migrations.CreateModel(
            name="BatchDocumentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("document_code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("source_step_key", models.CharField(blank=True, max_length=100)),
                ("is_required", models.BooleanField(default=True)),
                ("is_applicable", models.BooleanField(default=True)),
                (
                    "repeat_mode",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("per_shift", "Per shift"),
                            ("per_team", "Per team"),
                            ("per_box", "Per box"),
                            ("per_event", "Per event"),
                        ],
                        default="single",
                        max_length=32,
                    ),
                ),
                ("expected_count", models.PositiveIntegerField(default=1)),
                ("actual_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "Expected"),
                            ("present", "Present"),
                            ("missing", "Missing"),
                        ],
                        default="expected",
                        max_length=32,
                    ),
                ),
                ("applicability_basis_json", models.JSONField(blank=True, default=dict)),
                ("meta_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requirements",
                        to="batches.batch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "document_code"), name="uniq_batch_document_requirement"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BatchStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("step_key", models.CharField(max_length=100)),
                ("occurrence_key", models.CharField(default="default", max_length=200)),
                ("occurrence_index", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                ("sequence_order", models.PositiveIntegerField()),
                ("source_document_code", models.CharField(blank=True, max_length=100)),
                ("is_applicable", models.BooleanField(default=True)),
                ("applicability_basis_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("signed", "Signed"),
                            ("flagged", "Flagged"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                        ],
                        default="not_started",
                        max_length=32,
                    ),
                ),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("required", "Required"),
                            ("in_review", "In review"),
                            ("approved", "Approved"),
                            ("changed", "Changed"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "signature_state",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("required", "Required"),
                            ("signed", "Signed"),
                            ("changed", "Changed"),
                        ],
                        default="not_required",
                        max_length=32,
                    ),
                ),
                ("blocks_execution_progress", models.BooleanField(default=False)),
                ("blocks_step_completion", models.BooleanField(default=True)),
                ("blocks_signature", models.BooleanField(default=False)),
                ("blocks_pre_qa_handoff", models.BooleanField(default=True)),
                ("data_json", models.JSONField(default=dict)),
                ("meta_json", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="batches.batch",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edited_batch_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("sequence_order",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "step_key", "occurrence_key"),
                        name="uniq_batch_step_occurrence",
                    )
                ],
            },
        ),
    ]
