# Generated by Django 5.2.12 on 2026-03-14 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0001_initial"),
        ("mmr", "0001_initial_mmr_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="mmr_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="mmr.mmrversion",
            ),
        ),
        migrations.AddField(
            model_name="batchstep",
            name="has_open_exception",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="batchstep",
            name="open_exception_is_blocking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="batchstep",
            name="required_data_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("in_execution", "In execution"),
                    ("awaiting_pre_qa", "Awaiting pre-QA"),
                    ("review_required", "Review required"),
                    ("under_review", "Under review"),
                    ("released", "Released"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="batchstep",
            name="data_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="StepSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("meaning", models.CharField(max_length=100)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="step_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="batches.batchstep",
                    ),
                ),
            ],
            options={
                "ordering": ("-signed_at",),
            },
        ),
        migrations.CreateModel(
            name="DossierChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("is_present", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="batches.batch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "document_name"), name="uniq_batch_checklist_item"
                    )
                ],
            },
        ),
    ]
