# Generated by Django 5.2.12 on 2026-03-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepsignature",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signatures",
                to="batches.batchstep",
            ),
        ),
    ]
