# Generated by Django 5.2.12 on 2026-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0002_step_signature_protect_on_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchstep",
            name="data_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
