# Generated by Django 5.2.12 on 2026-03-13 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0002_step_signature_protect_on_delete"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"ordering": ["-created_at"], "verbose_name_plural": "batches"},
        ),
    ]
