# Generated by Django 5.2.12 on 2026-03-13 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0003_alter_batch_ordering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="batchstep",
            constraint=models.UniqueConstraint(
                fields=("batch", "sequence_order"), name="uniq_batch_sequence_order"
            ),
        ),
    ]
