# Generated by Django 5.2.12 on 2026-03-13 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_add_product_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("code",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
