# Generated by Django 5.2.12 on 2026-03-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('mmr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rules', models.JSONField(blank=True, default=dict, help_text='Conditional composition rules (JSONB).')),
                ('elements', models.JSONField(blank=True, default=list, help_text='Complete list of possible element identifiers for the template.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mmr_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dossier_profile', to='mmr.mmrversion')),
            ],
            options={
                'verbose_name': 'dossier profile',
                'verbose_name_plural': 'dossier profiles',
            },
        ),
        migrations.CreateModel(
            name='BatchDossierStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_snapshot', models.JSONField(help_text='Batch context attributes evaluated at resolution time.')),
                ('is_active', models.BooleanField(default=True, help_text='Only the latest active resolution is used. Old ones are kept for audit.')),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossier_structures', to='batches.batch')),
                ('dossier_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolved_structures', to='exports.dossierprofile')),
            ],
            options={
                'verbose_name': 'batch dossier structure',
                'verbose_name_plural': 'batch dossier structures',
                'ordering': ['-resolved_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_identifier', models.CharField(help_text='Reference identifier linking back to the template definition.', max_length=200)),
                ('element_type', models.CharField(choices=[('sub_document', 'Sub-document'), ('in_process_control', 'In-process control'), ('box_level_control', 'Box-level control'), ('checklist_item', 'Checklist item')], max_length=32)),
                ('display_order', models.PositiveIntegerField()),
                ('applicability', models.CharField(choices=[('required', 'Required'), ('not_applicable', 'Not applicable')], default='required', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional element-level metadata from the composition rules.')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='exports.batchdossierstructure')),
            ],
            options={
                'verbose_name': 'dossier element',
                'verbose_name_plural': 'dossier elements',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['structure', 'display_order'], name='exports_de_struct_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('structure', 'element_identifier'), name='exports_de_unique_element_per_structure')],
            },
        ),
        migrations.AddIndex(
            model_name='batchdossierstructure',
            index=models.Index(fields=['batch', 'is_active'], name='exports_bds_batch_active_idx'),
        ),
    ]
