# Generated by Django 5.2.12 on 2026-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("identify", "Identify"),
                    ("switch_user", "Switch User"),
                    ("lock_workstation", "Lock Workstation"),
                    ("lock_failed", "Lock Failed"),
                    ("identify_failed", "Identify Failed"),
                    ("signature_reauth_succeeded", "Signature Reauth Succeeded"),
                    ("signature_reauth_failed", "Signature Reauth Failed"),
                    ("mmr_created", "MMR Created"),
                    ("mmr_version_created", "MMR Version Created"),
                    ("mmr_version_step_added", "MMR Version Step Added"),
                    ("mmr_version_step_updated", "MMR Version Step Updated"),
                    ("mmr_version_step_removed", "MMR Version Step Removed"),
                    ("mmr_version_steps_reordered", "MMR Version Steps Reordered"),
                ],
                max_length=64,
            ),
        ),
    ]
