# Generated by Django 5.2.12 on 2026-03-13 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_alter_auditevent_event_type"),
        ("audit", "0006_remove_auditevent_audit_batch_event_actor_required_and_more"),
    ]

    operations = []
