# Generated by Django 5.2.12 on 2026-03-13 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0009_add_batch_access_viewed_events"),
        ("audit", "0009_alter_auditevent_event_type"),
    ]

    operations = []
