# Generated by Django 5.2.12 on 2026-03-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0010_merge_20260313_2336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("identify", "Identify"),
                    ("switch_user", "Switch User"),
                    ("lock_workstation", "Lock Workstation"),
                    ("lock_failed", "Lock Failed"),
                    ("identify_failed", "Identify Failed"),
                    ("signature_reauth_succeeded", "Signature Reauth Succeeded"),
                    ("signature_reauth_failed", "Signature Reauth Failed"),
                    ("mmr_created", "MMR Created"),
                    ("mmr_version_created", "MMR Version Created"),
                    ("batch_created", "Batch Created"),
                    ("step_draft_saved", "Step Draft Saved"),
                    ("step_completed", "Step Completed"),
                    ("step_signed", "Step Signed"),
                    ("batch_submitted_for_pre_qa", "Batch Submitted for Pre-QA"),
                    ("pre_qa_review_confirmed", "Pre-QA Review Confirmed"),
                    ("quality_review_started", "Quality Review Started"),
                    ("batch_released", "Batch Released"),
                    ("batch_rejected", "Batch Rejected"),
                    ("batch_returned_for_correction", "Batch Returned for Correction"),
                    ("correction_submitted", "Correction Submitted"),
                    ("change_reviewed", "Change Reviewed"),
                    ("batch_execution_viewed", "Batch Execution Viewed"),
                    ("batch_step_viewed", "Batch Step Viewed"),
                    ("dossier_resolved", "Dossier Resolved"),
                ],
                max_length=64,
            ),
        ),
    ]
