# Generated by Django 5.2.12 on 2026-03-14 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0010_alter_auditevent_event_type"),
        ("audit", "0011_alter_auditevent_event_type"),
    ]

    operations = []
