# Generated by Django 5.2.12 on 2026-03-13 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_add_product_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mmrs', to='sites.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mmrs', to='sites.site')),
            ],
            options={
                'verbose_name': 'MMR',
                'verbose_name_plural': 'MMRs',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='MMRVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_mmr_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mmr_versions', to=settings.AUTH_USER_MODEL)),
                ('mmr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='mmr.mmr')),
            ],
            options={
                'verbose_name': 'MMR Version',
                'verbose_name_plural': 'MMR Versions',
                'ordering': ('-version_number',),
            },
        ),
        migrations.AddConstraint(
            model_name='mmr',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='uniq_mmr_code_per_site'),
        ),
        migrations.AddConstraint(
            model_name='mmrversion',
            constraint=models.UniqueConstraint(fields=('mmr', 'version_number'), name='uniq_mmr_version_number'),
        ),
    ]
